"""Generation of a markdown file based on a yMMSL file."""

from pathlib import Path
from typing import List, Optional

import ymmsl

from .markdown_utilities import (
    demote_markdown_headers,
    format_title,
    markdown_table,
)


def ports_markdown(
    ports: dict,
    header_level: Optional[int] = None,
    header_text: Optional[str] = None,
) -> List[str]:
    """
    Generate Markdown lines for model or component ports.

    ports: Dictionary of port names to port objects.
    Optional: header level with header text.
    """
    if not ports:
        return []

    markdown_lines = []
    if header_level:
        markdown_lines.append(f"{header_level} {header_text}")

    headers = ["Operator", "Port Name"]
    rows = [(ports[port_name].operator.name, port_name) for port_name in ports]
    markdown_lines.extend([markdown_table(headers, rows), ""])
    return markdown_lines


def conduits_markdown(conduits: list, header_level: int = 4) -> List[str]:
    """
    Generate Markdown lines for conduits.
    """
    if not conduits:
        return []

    markdown_lines = [f"{header_level} Conduits"]
    for conduit in conduits:
        markdown_lines.append(f"* {conduit.sender}: {conduit.receiver}")
    markdown_lines.append("")
    return markdown_lines


def component_markdown(comp_name: str, component) -> List[str]:
    """
    Generate Markdown lines for a single component.
    """
    markdown_lines = [f"#### {format_title(comp_name)}"]

    if component.description:
        comp_desc = demote_markdown_headers(component.description.strip(), level=4)
        markdown_lines.extend([comp_desc, ""])

    markdown_lines.extend(ports_markdown(component.ports))
    markdown_lines.extend([f"**Implementation**: `{component.implementation}`", ""])
    markdown_lines.extend([f"**Multiplicity**: `{component.multiplicity}`", ""])

    return markdown_lines


def components_markdown(components: dict) -> List[str]:
    """
    Generate Markdown lines for all components, where the markdown for each component is
    generated by generate_component_markdown().
    """
    if not components:
        return []

    markdown_lines = []
    for comp_name, component in components.items():
        markdown_lines.extend(component_markdown(comp_name, component))

    return markdown_lines


def generate_supported_settings_markdown(supported_settings: list) -> List[str]:
    """
    Generate Markdown lines for supported settings.

    Args:
        supported_settings: List of (parameter_name, setting) tuples.

    Returns:
        List of markdown lines representing the supported settings table.
    """
    if not supported_settings:
        return []

    markdown_lines = ["#### Supported Settings"]
    headers = ["Parameter", "Type", "Description"]
    rows = [
        (param_name, str(setting.typ), setting.description or "")
        for param_name, setting in supported_settings
    ]
    markdown_lines.extend([markdown_table(headers, rows), ""])

    markdown_lines.append(
        "For more information about the types: [yMMSL documentation](https://ymmsl-python.readthedocs.io/en/develop/index.html)."
    )
    markdown_lines.append("")

    return markdown_lines


def generate_header(
    title: str,
    description: Optional[str] = None,
    header_level: int = 1,
) -> List[str]:
    """
    Generate Markdown lines for a header with optional description.

    header_level: The markdown header level (1 for #, 2 for ##, 3 for ###, etc.).
                    Also used as the level for demoting headers in the description.
    """
    header_prefix = "#" * header_level
    markdown_lines = [f"{header_prefix} {title}"]

    if description:
        desc = demote_markdown_headers(description.strip(), level=header_level)
        markdown_lines.extend([desc, ""])

    return markdown_lines


def generate_document_header(ymmsl_path: Path, description: Optional[str]) -> List[str]:
    """
    Generate Markdown lines for the document header: title and optional description.
    """
    title = f"yMMSL {format_title(ymmsl_path.stem)} Documentation"
    return generate_header(title, description, header_level=1)


def generate_model_header(model_name: str, description: Optional[str]) -> List[str]:
    """
    Generate Markdown lines for a model header and description.
    """
    title = format_title(model_name)
    return generate_header(title, description, header_level=3)


def extract_version_from_file(ymmsl_path: Path) -> Optional[str]:
    """
    Extract the yMMSL version from a yMMSL file.
    """
    for line in ymmsl_path.read_text().splitlines():
        if line.startswith("ymmsl_version:"):
            return line.split(":", 1)[1].strip()
    return None


def generate_file_info(ymmsl_path: Path) -> List[str]:
    """
    Generate Markdown lines for file information: filename and yMMSL version.
    """
    markdown_lines = [f"**Model file**: `{ymmsl_path.name}`", ""]

    version = extract_version_from_file(ymmsl_path)
    if version:
        markdown_lines.append(f"**yMMSL version**: `{version}`")

    markdown_lines.append("")
    return markdown_lines


def model_markdown(cfg: ymmsl.v0_2.Configuration) -> str:
    """
    Generate Markdown documentation for models in a yMMSL configuration.

    The generated documentation includes:
    - Model titles along with their descriptions.
    - Conduits listed as bullet points.
    - Components with their descriptions, ports presented in tables, implementation, and
      multiplicity.
    - A table of supported settings for each model.
    """
    if not cfg.models:
        return ""

    markdown_lines = ["## Models", ""]

    for model_name, model_data in cfg.models.items():
        markdown_lines.extend(generate_model_header(model_name, model_data.description))
        markdown_lines.extend(
            ports_markdown(model_data.ports, header_level=3, header_text="Model Ports")
        )
        markdown_lines.extend(conduits_markdown(model_data.conduits))
        markdown_lines.extend(components_markdown(model_data.components))
        markdown_lines.extend(
            generate_supported_settings_markdown(model_data.supported_settings)
        )

    return "\n".join(markdown_lines)


def ymmsl_to_markdown(ymmsl_path: Path) -> str:
    """
    Generate complete Markdown documentation for a yMMSL file.

    The documentation includes:
        - A title based on the yMMSL file name.
        - The configuration description, if available.
        - The yMMSL file name and version.
        - Detailed model documentation defined by model_markdown_generation.
    """
    cfg = ymmsl.load_as(ymmsl.v0_2.Configuration, ymmsl_path)

    markdown_lines = []
    markdown_lines.extend(generate_document_header(ymmsl_path, cfg.description))
    markdown_lines.extend(generate_file_info(ymmsl_path))
    markdown_lines.append(model_markdown(cfg))

    return "\n".join(markdown_lines)
